#!/bin/bash
#
# Return name of active audio device (headphone, speaker, or bt friendly name) 
# Dependencies: bluez-tools

# These are hardcoded due to not knowing a better way to do it
# You can find these by uncommenting line 15. I'll make a function later 
headphone=45874
speakers=65536
a_sink=$(pacmd list-sinks | awk '/* index:/{print $3}')
sink_name=$(pactl list short sinks | grep ^${a_sink} | awk -F '\t' '{print $2}' | awk -F '_' '{print $1}')
mac=$(pactl list short sinks | grep ${sink_name} | awk -F '\t' '{print $2}' | awk -F '.' '{print $2}' | sed 's/_/:/g')
bt_name=$(bt-device -l | grep ${mac} | awk -F ' \\(' '{print $1}')
hp_or_spk=$(amixer -D pulse sget Master | grep "Front Left:" | awk -F ' ' '{print $4}')
# echo $hp_or_spk

if [[ $bt_name != "" ]]; then
  echo "${bt_name}"
else
  if [[ "$hp_or_spk" == "$headphone" ]]; then
    echo "Headphones"
  else
    echo "Speakers"
  fi
fi
