#! /bin/bash
#
# Creates an image file from ID3 of current song

cover=/tmp/cover.jpg

if [ -f ${cover} ]; then
  rm ${cover}
fi

{ IFS=$(echo -en "\n\b")
  file="$(mpc --format [%file%] current)"
  cover_in_dir=~/Music/${file%\/*}/cover.jpg

  if [ -f ${cover_in_dir} ]; then
    cp ${cover_in_dir} /tmp
  else
    ffmpeg -loglevel quiet -vsync 2 -i ~/Music/${file} ${cover}
  fi
}
