#!/bin/bash
#
# Display a notification with system information

date=$(date +"%a, %b %d %Y")
time=$(date +%H:%M)
batt=$(~/.config/.scripts/battery)
inet=$(~/.config/.scripts/netiface)
netbar=$(~/.config/.scripts/wifidotmeter)
vol=$(~/.config/.scripts/volume)
snd=$(~/.config/.scripts/active_audio)
ws=$(~/.config/.scripts/current_ws)

if [[ "$inet" == Wifi* ]]; then
  ssid=$(~/.config/conky/scripts/wifimeter -d)
else
  ssid=""
fi

notify-send -t 20000 "$(echo -e "$time\t$date\n$ws\n\n$batt\n$inet $ssid\n$vol ($snd)")" -h string:synchronous:stat
