#! /bin/bash

# a script to display the os, shamelessly taken from aurafetch so I don't have to do extra work

if [ -f '/etc/lsb-release' ]; then
  os=$(grep 'DISTRIB_ID=' /etc/lsb-release)
  os=${os/*=}
  osv=$(grep 'DISTRIB_RELEASE=' /etc/lsb-release)
  osv=${osv/*=}
else
  os=$(grep '^ID=' /etc/os-release)
  os=${os/*=}
  osv=$(grep '^VERSION_ID=' /etc/os-release)
  osv=${osv/*=}
fi
os=${os,,}

echo $os $osv
