#!/bin/bash

# A simple script to show recent non-live scores for an NHL team

TEAMPAGE="http://www.espn.com/nhl/team/_/name/nyr/new-york-rangers"
SCHEDULE=$(lynx --dump "${TEAMPAGE}" | sed -n '/Regular Season/,/Full Schedule/{//!p}' | sed 's/^[ \t]*//;s/[ \t]*$//' | sed -r '/^\s*$/d' | sed 'n;n;G;' | paste - - | paste - -)
THREE_MOST_RECENT_GAMES=$(echo "${SCHEDULE}" | head -3)
NEXT_GAME=$(echo "${THREE_MOST_RECENT_GAMES}" | head -1 | awk -F '\t' '{print "Rangers " $1, $2}')
LAST_GAME=$(echo "${THREE_MOST_RECENT_GAMES}" | tail -2 | head -1)
LAST_GAME_SCORE=$(echo ${LAST_GAME} | awk -F ' ' '{print $3}')
LAST_GAME_OPPONENT=$(echo ${LAST_GAME} | awk -F ' ' '{print $2}')
LAST_LAST_GAME=$(echo "${THREE_MOST_RECENT_GAMES}" | tail -1 | awk -F '\t' '{print "Rangers " $1,$2}')

# echo "${THREE_MOST_RECENT_GAMES}"
echo $NEXT_GAME
# echo $LAST_GAME_SCORE
echo $LAST_GAME
# echo $LAST_GAME_OPPONENT
echo $LAST_LAST_GAME
