#!/bin/bash

killall -q ncmpcpp
killall -q cava
while pgrep -u $UID -x ncmpcpp >/dev/null; do sleep 1; done

if [[ $(lsof -i :6600) ]]; then
  echo "mpd running"
else
  echo "launching mpd"
  mpd
fi

echo "launching ncmpcpp"
alacritty --config-file ~/.config/alacritty/ncmpcpp.yml -e ncmpcpp -c ~/.ncmpcpp/config &
echo "launching cava"
alacritty --config-file ~/.config/alacritty/cava.yml -t cava -e cava &

echo "done"
exit 0
