#!/bin/bash
#
# Sends a notification of current song and album art (if it exists)

icon=/tmp/cover.jpg
song=$(mpc current)

dunstify --replace=369 -a ncmpcpp -t 10000 "Now Playing:" "$song" -i $icon

exit 0
