#!/bin/bash
#
# Sends a notification of current song and album art (if it exists)

icon=/tmp/cover.jpg
song=$(mpc current)
state=$(mpc status %state%)
state="${state^}"

dunstify --replace=369 -a ncmpcpp -t 10000 "${state}" "$song" -i $icon

exit 0
