#!/bin/bash

INFO=$(iwconfig wlp3s0)
LEVEL=$(echo $INFO | grep -o "Signal level=.*dBm" | sed 's/Signal level=\(-[0-9]*\).*/\1/')
blank="▫"
fill="▪"
# blank="○"
# fill="●"

# if [ -z "$LEVEL" ]; then
#   echo ""
# elif (( $LEVEL -gt -49 )); then
#   echo "●●●●●"
# elif [ $LEVEL -gt -59 ]; then 
#   echo "●●●●○"
# elif [ $LEVEL -gt -69 ]; then
#   echo "●●●○○"
# elif [ $LEVEL -gt -79 ]; then
#   echo "●●○○○"
# elif [ $LEVEL -gt -89 ]; then
#   echo "●○○○○"
# else 
#   echo "○○○○○"
# fi

print_bar () {

  step=$((( $LEVEL + 99 ) / 10 )) 

  for i in 1 2 3 4 5
  do
    if (( $i <= $step )); then
      strength+=$fill
    else
      strength+=$blank
    fi
  done

  echo $strength
}
print_bar
