#!/bin/bash

# INFO=$(iwconfig wlp3s0)
INFO=$(iwconfig wlan0)
LEVEL=$(echo $INFO | grep -o "Signal level=.*dBm" | sed 's/Signal level=\(-[0-9]*\).*/\1/')
# blank="▫"
# fill="▪"
blank="○"
fill="●"

print_bar () {

  step=$((( $LEVEL + 99 ) / 10 )) 

  for i in 1 2 3 4 5
  do
    if (( $i <= $step )); then
      strength+=$fill
    else
      strength+=$blank
    fi
  done

  echo $strength
}
print_bar
