#!/bin/bash

if command -v nmcli &> /dev/null; then
  device="$(nmcli -g device con show -a | grep '^[ew]')"
elif command -v route &> /dev/null; then
  device="$(route | grep '^default' | head -1 | awk -F ' ' '{print $8}')"
fi 

if [[ "$device" == w* ]]; then
  if command -v iwconfig &> /dev/null; then
    info=$(iwconfig $device)
  fi
elif [[ "$device" == e* ]]; then
  info="Ethernet"
else
  info="Device info not found"
fi

level=$(echo $info | grep -o "Signal level=.*dBm" | sed 's/Signal level=\(-[0-9]*\).*/\1/')
# blank="▫"
# fill="▪"
blank="○"
fill="●"

print_bar () {

  step=$((( $level + 99 ) / 10 )) 

  for i in 1 2 3 4 5
  do
    if (( $i <= $step )); then
      strength+=$fill
    else
      strength+=$blank
    fi
  done

  echo $strength
}

if [[ "$device" == *w ]]; then
  print_bar
else
  echo $info
fi

